---
include:
  - board: seeeduino_xiao_ble
    shield: MKB_L rgbled_adapter dongle_display
    snippet: zmk-usb-logging studio-rpc-usb-uart
    artifact-name: MKB_L_MODULE_TB
    cmake-args: "-DCONFIG_MKB_L_MODULE_TB:BOOL=y"

  - board: seeeduino_xiao_ble
    shield: MKB_L rgbled_adapter dongle_display
    snippet: zmk-usb-logging studio-rpc-usb-uart
    artifact-name: MKB_L_MODULE_JOY
    cmake-args: "-DCONFIG_MKB_L_MODULE_JOY:BOOL=y"

  - board: seeeduino_xiao_ble
    shield: MKB_L rgbled_adapter dongle_display
    snippet: zmk-usb-logging studio-rpc-usb-uart
    artifact-name: MKB_L_MODULE_ENC
    cmake-args: "-DCONFIG_MKB_L_MODULE_ENC:BOOL=y"

  - board: seeeduino_xiao_ble
    shield: MKB_R rgbled_adapter
    snippet: zmk-usb-logging studio-rpc-usb-uart

  - board: seeeduino_xiao_ble
    shield: settings_reset