---
include:
  - board: seeeduino_xiao_ble
    shield: MKB_L rgbled_adapter dongle_display
    snippet: zmk-usb-logging studio-rpc-usb-uart
    artifact-name: MKB_L_MODULE_TB
    cmake-args: "-DMY_BOARD_VARIANT=trackball -DCONFIG_MKB_L_MODULE_TB=y"

  - board: seeeduino_xiao_ble
    shield: MKB_L rgbled_adapter dongle_display
    snippet: zmk-usb-logging studio-rpc-usb-uart
    artifact-name: MKB_L_MODULE_JOY
    cmake-args: "-DMY_BOARD_VARIANT=joystick -DCONFIG_MKB_L_MODULE_JOY=y"

  - board: seeeduino_xiao_ble
    shield: MKB_L rgbled_adapter dongle_display
    snippet: zmk-usb-logging studio-rpc-usb-uart
    artifact-name: MKB_L_MODULE_ENC
    cmake-args: "-DMY_BOARD_VARIANT=encoder -DCONFIG_MKB_L_MODULE_ENC=y"

  - board: seeeduino_xiao_ble
    shield: MKB_R rgbled_adapter
    snippet: zmk-usb-logging studio-rpc-usb-uart

  - board: seeeduino_xiao_ble
    shield: settings_reset