---
include:
  - board: seeeduino_xiao_ble
    shield: MKB_L
    cmake-args: "-DSHIELD_MKB_L=y -DCONFIG_MKB_L_MODULE_TB=y"
    artifact-name: left_tb

  - board: seeeduino_xiao_ble
    shield: MKB_L
    cmake-args: "-DSHIELD_MKB_L=y -DCONFIG_MKB_L_MODULE_JOY=y"
    artifact-name: left_joy

  - board: seeeduino_xiao_ble
    shield: MKB_L
    cmake-args: "-DSHIELD_MKB_L=y -DCONFIG_MKB_L_MODULE_ENC=y"
    artifact-name: left_enc

  - board: seeeduino_xiao_ble
    shield: MKB_R
    artifact-name: right

  - board: seeeduino_xiao_ble
    shield: settings_reset