---
include:
  - board: seeeduino_xiao_ble
    shield: MKB_L rgbled_adapter
    snippet: zmk-usb-logging studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: MKB_R rgbled_adapter
    snippet: zmk-usb-logging studio-rpc-usb-uart
  - board: seeeduino_xiao_ble
    shield: settings_reset